language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: HS2AXOMYtbPdmJGhelS2TjFqlj96Ih5foPm2WeSgjLSOd3Ike40yRHDXGUrKTl3bLvu0DbZ3A4zf8n+vjMuxzaAuvZtMIbgpFJR7J0BH3ydxWjUdvQnZ/EdtXLSaZ3+L8bwBJLKXFF9BPoiIru6hglc39O0TKOphGXGar82OxNhze7Sw5DLIHkvq84L2q3k+ebFpcgTDXgDHyQRDaxoL64FNB9UtxRGhmrVOLg51RlfbBxYxDNbbvoYUaXFQQUu/jAVC7MM2+9YUlzFpFMqZ75Lmm1QpVNcj9dKch5z/WLrs/Q8l3yIk1xERS/6HXgNNlbMr0bdkpHgR6OyprKr4HER5wWD+6LMzC+dXAt/8LDyOkNZ//M5UaniZwPXZt6xHnOa/1/dlxanMsBs0VHNTQ5nSWQrXavcblcVepddLw4UfKmenoU5q2vc8kZaPaFB/YUvq52ks3DEqoGAg9gBNhDf2/HJT6zamFjoC6jkvvoAAmnmoRQKLDGC5jUNDxhmiROyt4k19M6dadOBIbiX9BVDv8z2Kd5jM228qQO1CwJqpxVPeMSB9RBLuD7Pt38XgYqxjnC6B3VrxVZt3HwUHVmt48Hc8rSoRMjbEkJQgwE6iFcOjgrQ6RIIPjZW1Y3Y0S78HGgL0PMx5uTHQg+bhWor4ji/6bD+Sr5F0+eu+iXs=
  app: libraryapp-3130
  on:
    repo: jackson211/LibraryApp
